name: Build and Deploy Bookdown Site to Netlify

on:
  push:
    branches:
      - main   # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install R dependencies (Bookdown, Rmarkdown)
      - name: Install dependencies
        run: |
          install.packages("bookdown")
          install.packages("rmarkdown")

      # Step 4: Build the Bookdown site
      - name: Build Bookdown site
        run: |
          Rscript -e "bookdown::render_book()"

      # Step 5: Install Netlify CLI and deploy
      - name: Install Netlify CLI
        run: |
          npm install netlify-cli -g

      # Step 6: Deploy to Netlify
      - name: Deploy to Netlify
        run: |
          netlify deploy --dir=_book --prod --token ${{ secrets.NETLIFY_AUTH_TOKEN }}
